- solr/conf/solrconfig.xml
Update solrConfig to keep in line with solr-trove version
> fix: enable arclight transaction log

- nla-deploy.sh
Same as https://github.com/nla/nla-blacklight/pull/322
> fix: fixes vendor/bundle permissions on deployment

- app/controllers/catalog_controller.rb
Upgraded with some changes to CatalogController from ArcLight.
> chore: upgraded CatalogController from ArcLight [BLAC-193]

- app/assets/stylesheets/nla/_nla-arclight.scss
- app/assets/stylesheets/nla/_record.scss
Updated styling on
- Online icon
- Which tab is highlighted
- "View online" link to a primary button
For the "View online" button, I tried finding the right component to update as it would be much easier to assign CSS classes of class="bin bin-primary" directly to the link. Instead I recreated the button styles in CSS which is a bit dodgy.
> BLAC-312: Style Arclight record page

- app/assets/stylesheets/nla/_header.scss
- app/controllers/catalog_controller.rb
- app/views/blacklight/nav/_bookmark.html.erb
- app/views/shared/_user_util_links.html.erb
- config/locales/blacklight.en.yml
- Direct links to each search target
- Move "User" functions to drop down menu
> BLAC-333: Restyle primary navigation

- config/downloads.yml
- config/repositories.yml
Hides "Request" button and download links until they're properly implemented.
> feat: disable request and download links

- app/assets/stylesheets/nla/_header.scss
- app/controllers/catalog_controller.rb
- app/views/shared/nav/_ask_a_librarian.html.erb
- app/views/shared/nav/_help.html.erb
- config/locales/blacklight.en.yml
Add Ask a librarian and help to header nav
> BLAC-333: Add links to header

- Gemfile.lock
- app/assets/stylesheets/nla/_header.scss
- app/views/shared/nav/_finding_aids.html.erb
- bin/setup
Pulls in helper from `nla-blacklight_common` and adds active link style to navbar.
> feat: add active link to navbar

- app/assets/stylesheets/nla/_buttons.scss
- app/views/bookmarks/_clear_bookmarks_widget.html.erb
Sorry - one minor thing I missed in the main BLAC-331 PR
> BLAC-331 (a): Clear bookmarks button styling

- app/assets/stylesheets/nla/_nla-custom-bootstrap.scss
- app/assets/stylesheets/nla/_record.scss
- app/assets/stylesheets/nla/_search-results.scss
Colour contrast fixes for box info & highlighted rows
> BLAC-468: Colour contrast to meet WCAG

- app/views/shared/nav/_help.html.erb
Sorry - last minute change from Reader Services
> BLAC-483: Update URL for help

- .env.staging
- Gemfile
- Gemfile.lock
- config/environments/development.rb
- nla-deploy.sh
Fixed caching in the Devel env and added the call to clear the Redis cache on deploy.
> chore: prepare Sprint 6

- app/views/shared/_header_navbar.html.erb
BLAC-515: Show login on tablet
> chore: merge changes from main

- app/assets/stylesheets/nla/_facets.scss
Sorry, Just one very small fix for some bright green text showing up in the year chart modal.
> BLAC-464: change green text in modal to grey

- app/models/solr_document.rb
- config/locales/arclight.en.yml
- spec/models/solr_document_spec.rb
implemented business text/formatting request
> BLAC-654: update text and formatting

- .env.development
- .env.staging
- .env.test
- Gemfile.lock
- app/views/shared/_user_util_links.html.erb
- spec/support/webmock.rb
- spec/system/nav_actions_spec.rb
Disables login when FOLIO is updating.
> feat: disable login during FOLIO updates

- app/views/layouts/blacklight/base.html.erb
same vein as: https://github.com/nla/nla-blacklight/pull/1119
> remove skip links

- .env.development
- .env.staging
- app/components/blacklight/top_navbar_component.html.erb
- app/controllers/catalog_controller.rb
- app/views/shared/_footer.html.erb
- app/views/shared/_user_util_links.html.erb
- app/views/shared/nav/_ask_a_librarian.html.erb
- app/views/shared/nav/_help.html.erb
- config/repositories.yml
Now that the final production site for library.gov.au is live (behind the password), can update all URL's to their final versions.
> CTPL-265: Update links to new pages at library.gov.au

- app/assets/stylesheets/nla/_dark-mode.scss
Forgot to do a pull request for this for the current Feb release. Can this please get incorporated into the next release
> CTPL-315: Change colour of remove facet icon in dark mode

- app/views/shared/_footer.html.erb
so it isn't read out by screen readers
> CTPL-307: Remove book curl image in footer from accessibility tree 

- app/components/blacklight/search_bar_component.html.erb
- app/components/blacklight/search_bar_component.rb
- app/components/blacklight/search_navbar_component.html.erb
Remove superfluous aria roles & change order of form field labels
> CTPL-327: Improve search form for screen readers

- app/assets/stylesheets/nla/_dark-mode.scss
- config/repositories.yml
- Logo
- Text contrast in dark mode
> CTPL-410: Fix display of repositories page
